Cleanup release tasks
Signed-off-by: Kevin Ullyott <kevin.ullyott@canyongbs.com>

diff --git a/docker/release-automation/s6-overlay/scripts/generate-api-docs b/docker/release-automation/s6-overlay/scripts/generate-api-docs
--- a/docker/release-automation/s6-overlay/scripts/generate-api-docs
+++ b/docker/release-automation/s6-overlay/scripts/generate-api-docs
@@ -9,14 +9,14 @@ cd "$WEBUSER_HOME" || exit 0
 
 echo "Generating API documentation..."
 
-  {
-    USERNAME=$(id -nu "$PUID")
+{
+USERNAME=$(id -nu "$PUID")
 
-    s6-setuidgid "$USERNAME" php "$WEBUSER_HOME/artisan" api:print-schema \
-    && s6-setuidgid "$USERNAME" npm run api-docs:generate \
-    && echo "API documentation generation complete!"
-  } || {
-    echo "API documentation generation failed!"
-  }
+s6-setuidgid "$USERNAME" php "$WEBUSER_HOME/artisan" api:print-schema \
+&& s6-setuidgid "$USERNAME" npm run api-docs:generate \
+&& echo "API documentation generation complete!"
+} || {
+echo "API documentation generation failed!"
+}
 
 exit 0
diff --git a/docker/release-automation/s6-overlay/scripts/laravel-migrate b/docker/release-automation/s6-overlay/scripts/laravel-migrate
--- a/docker/release-automation/s6-overlay/scripts/laravel-migrate
+++ b/docker/release-automation/s6-overlay/scripts/laravel-migrate
@@ -9,34 +9,26 @@ cd "$WEBUSER_HOME" || exit 0
 
 USERNAME=$(id -nu "$PUID")
 
-if [ "${LANDLORD_MIGRATE:="true"}" == "true" ]; then
-  echo "Starting landlord migrations..."
+echo "Starting landlord migrations..."
 
-  {
-    s6-setuidgid "$USERNAME" php "$WEBUSER_HOME/artisan" migrate --database=landlord --path=database/landlord --force --isolated \
-    && echo "Landlord migrations completed!"
-  } || {
-    echo "Landlord migrations failed!"
+{
+s6-setuidgid "$USERNAME" php "$WEBUSER_HOME/artisan" migrate --database=landlord --path=database/landlord --force --isolated \
+&& echo "Landlord migrations completed!"
+} || {
+echo "Landlord migrations failed!"
 
-    # TODO: Do something to send an alert that landlord migrations failed. Currently this will NOT stop the container.
-  }
-else
-    echo "Skipping landlord migrations because it was specifically disabled..."
-fi
+# TODO: Do something to send an alert that landlord migrations failed. Currently this will NOT stop the container.
+}
 
-if [ "${TENANT_MIGRATE:="true"}" == "true" ]; then
-  echo "Starting tenant migrations..."
+echo "Starting tenant migrations..."
 
-  {
-    s6-setuidgid "$USERNAME" php "$WEBUSER_HOME/artisan" tenants:artisan "migrate --database=tenant --force --isolated" \
-    && echo "Tenant migrations completed!"
-  } || {
-    echo "Tenant migrations failed!"
+{
+s6-setuidgid "$USERNAME" php "$WEBUSER_HOME/artisan" tenants:artisan "migrate --database=tenant --force --isolated" \
+&& echo "Tenant migrations completed!"
+} || {
+echo "Tenant migrations failed!"
 
-    # TODO: Do something to send an alert that tenant migration failed. Currently this will NOT stop the container.
-  }
-else
-    echo "Skipping tenant migrations because it was specifically disabled..."
-fi
+# TODO: Do something to send an alert that tenant migration failed. Currently this will NOT stop the container.
+}
 
 exit 0
