Restore commented out steps in deployment actions
Signed-off-by: Kevin Ullyott <kevin.ullyott@canyongbs.com>

diff --git a/.github/workflows/prerelease.yml b/.github/workflows/prerelease.yml
--- a/.github/workflows/prerelease.yml
+++ b/.github/workflows/prerelease.yml
@@ -88,21 +88,21 @@ jobs:
               uses: aws-actions/amazon-ecs-deploy-task-definition@a310a830f5c14e583e35d84e4e1ec7dd177c3c9c #2.6.2
               with:
                   task-definition: ${{ steps.task-def.outputs.task-definition }}
-                  # service: 'advisingapp-dev-service'
-                  # cluster: 'advisingapp-dev'
-                  # wait-for-service-stability: true
+                  service: 'advisingapp-dev-service'
+                  cluster: 'advisingapp-dev'
+                  wait-for-service-stability: true
 
-            # - name: Check if deployment was successful
-            #   id: check-deployment
-            #   run: |
-            #       CURRENT_TASK_DEF_ARN=$(aws ecs describe-services --cluster advisingapp-dev --services advisingapp-dev-service --query services[0].deployments[0].taskDefinition | jq -r ".")
-            #       NEW_TASK_DEF_ARN=${{ steps.task-deploy.outputs.task-definition-arn }}
-            #       echo "Current task arn: $CURRENT_TASK_DEF_ARN"
-            #       echo "New task arn: $NEW_TASK_DEF_ARN"
-            #       if [ "$CURRENT_TASK_DEF_ARN" != "$NEW_TASK_DEF_ARN" ]; then
-            #         echo "Deployment failed."
-            #         exit 1
-            #       fi
+            - name: Check if deployment was successful
+              id: check-deployment
+              run: |
+                  CURRENT_TASK_DEF_ARN=$(aws ecs describe-services --cluster advisingapp-dev --services advisingapp-dev-service --query services[0].deployments[0].taskDefinition | jq -r ".")
+                  NEW_TASK_DEF_ARN=${{ steps.task-deploy.outputs.task-definition-arn }}
+                  echo "Current task arn: $CURRENT_TASK_DEF_ARN"
+                  echo "New task arn: $NEW_TASK_DEF_ARN"
+                  if [ "$CURRENT_TASK_DEF_ARN" != "$NEW_TASK_DEF_ARN" ]; then
+                    echo "Deployment failed."
+                    exit 1
+                  fi
 
     build-worker:
         name: Build Worker Image
@@ -184,21 +184,21 @@ jobs:
               uses: aws-actions/amazon-ecs-deploy-task-definition@a310a830f5c14e583e35d84e4e1ec7dd177c3c9c #2.6.2
               with:
                   task-definition: ${{ steps.task-def.outputs.task-definition }}
-                  # service: 'advisingapp-worker-dev-service'
-                  # cluster: 'advisingapp-dev'
-                  # wait-for-service-stability: true
+                  service: 'advisingapp-worker-dev-service'
+                  cluster: 'advisingapp-dev'
+                  wait-for-service-stability: true
 
-            # - name: Check if deployment was successful
-            #   id: check-deployment
-            #   run: |
-            #       CURRENT_TASK_DEF_ARN=$(aws ecs describe-services --cluster advisingapp-dev --services advisingapp-worker-dev-service --query services[0].deployments[0].taskDefinition | jq -r ".")
-            #       NEW_TASK_DEF_ARN=${{ steps.task-deploy.outputs.task-definition-arn }}
-            #       echo "Current task arn: $CURRENT_TASK_DEF_ARN"
-            #       echo "New task arn: $NEW_TASK_DEF_ARN"
-            #       if [ "$CURRENT_TASK_DEF_ARN" != "$NEW_TASK_DEF_ARN" ]; then
-            #         echo "Deployment failed."
-            #         exit 1
-            #       fi
+            - name: Check if deployment was successful
+              id: check-deployment
+              run: |
+                  CURRENT_TASK_DEF_ARN=$(aws ecs describe-services --cluster advisingapp-dev --services advisingapp-worker-dev-service --query services[0].deployments[0].taskDefinition | jq -r ".")
+                  NEW_TASK_DEF_ARN=${{ steps.task-deploy.outputs.task-definition-arn }}
+                  echo "Current task arn: $CURRENT_TASK_DEF_ARN"
+                  echo "New task arn: $NEW_TASK_DEF_ARN"
+                  if [ "$CURRENT_TASK_DEF_ARN" != "$NEW_TASK_DEF_ARN" ]; then
+                    echo "Deployment failed."
+                    exit 1
+                  fi
 
     build-scheduler:
         name: Build Scheduler Image
@@ -280,106 +280,106 @@ jobs:
               uses: aws-actions/amazon-ecs-deploy-task-definition@a310a830f5c14e583e35d84e4e1ec7dd177c3c9c #2.6.2
               with:
                   task-definition: ${{ steps.task-def.outputs.task-definition }}
-                  # service: 'advisingapp-scheduler-dev-service'
-                  # cluster: 'advisingapp-dev'
-                  # wait-for-service-stability: true
+                  service: 'advisingapp-scheduler-dev-service'
+                  cluster: 'advisingapp-dev'
+                  wait-for-service-stability: true
 
-            # - name: Check if deployment was successful
-            #   id: check-deployment
-            #   run: |
-            #       CURRENT_TASK_DEF_ARN=$(aws ecs describe-services --cluster advisingapp-dev --services advisingapp-scheduler-dev-service --query services[0].deployments[0].taskDefinition | jq -r ".")
-            #       NEW_TASK_DEF_ARN=${{ steps.task-deploy.outputs.task-definition-arn }}
-            #       echo "Current task arn: $CURRENT_TASK_DEF_ARN"
-            #       echo "New task arn: $NEW_TASK_DEF_ARN"
-            #       if [ "$CURRENT_TASK_DEF_ARN" != "$NEW_TASK_DEF_ARN" ]; then
-            #         echo "Deployment failed."
-            #         exit 1
-            #       fi
+            - name: Check if deployment was successful
+              id: check-deployment
+              run: |
+                  CURRENT_TASK_DEF_ARN=$(aws ecs describe-services --cluster advisingapp-dev --services advisingapp-scheduler-dev-service --query services[0].deployments[0].taskDefinition | jq -r ".")
+                  NEW_TASK_DEF_ARN=${{ steps.task-deploy.outputs.task-definition-arn }}
+                  echo "Current task arn: $CURRENT_TASK_DEF_ARN"
+                  echo "New task arn: $NEW_TASK_DEF_ARN"
+                  if [ "$CURRENT_TASK_DEF_ARN" != "$NEW_TASK_DEF_ARN" ]; then
+                    echo "Deployment failed."
+                    exit 1
+                  fi
 
-    # build-release-automation:
-    #     name: Build Release Automation Image
-    #     runs-on: ubuntu-22.04
-    #     outputs:
-    #         image: ${{ steps.build-image.outputs.image }}
-    #     environment: staging
+    build-release-automation:
+        name: Build Release Automation Image
+        runs-on: ubuntu-22.04
+        outputs:
+            image: ${{ steps.build-image.outputs.image }}
+        environment: staging
 
-    #     steps:
-    #         - name: Checkout
-    #           uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #6.0.2
-    #           with:
-    #               submodules: true
-    #               ref: ${{ github.head_ref }}
-    #               token: ${{ secrets.PAT }}
+        steps:
+            - name: Checkout
+              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #6.0.2
+              with:
+                  submodules: true
+                  ref: ${{ github.head_ref }}
+                  token: ${{ secrets.PAT }}
 
-    #         - name: Login to Docker Hub
-    #           uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 #4.1.0
-    #           with:
-    #               username: ${{ secrets.DOCKERHUB_USERNAME }}
-    #               password: ${{ secrets.DOCKERHUB_PASSWORD }}
+            - name: Login to Docker Hub
+              uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 #4.1.0
+              with:
+                  username: ${{ secrets.DOCKERHUB_USERNAME }}
+                  password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
-    #         - name: Configure AWS credentials
-    #           uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 #6.1.0
-    #           with:
-    #               aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
-    #               aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
-    #               aws-region: ${{ env.AWS_REGION }}
+            - name: Configure AWS credentials
+              uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 #6.1.0
+              with:
+                  aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
+                  aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
+                  aws-region: ${{ env.AWS_REGION }}
 
-    #         - name: Login to Amazon ECR
-    #           id: login-ecr
-    #           uses: aws-actions/amazon-ecr-login@19d944daaa35f0fa1d3f7f8af1d3f2e5de25c5b7 #2.1.4
+            - name: Login to Amazon ECR
+              id: login-ecr
+              uses: aws-actions/amazon-ecr-login@19d944daaa35f0fa1d3f7f8af1d3f2e5de25c5b7 #2.1.4
 
-    #         - name: Build, tag, and push image to Amazon ECR
-    #           id: build-image
-    #           env:
-    #               ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-    #               IMAGE_TAG: ${{ github.event.release.tag_name }}
-    #               ECR_REPOSITORY: 'advisingapp/release-automation'
-    #           run: |
-    #               # Build a docker container and
-    #               # push it to ECR so that it can
-    #               # be deployed to ECS.
-    #               docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --target release-automation --platform linux/amd64 .
-    #               docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
-    #               echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
+            - name: Build, tag, and push image to Amazon ECR
+              id: build-image
+              env:
+                  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+                  IMAGE_TAG: ${{ github.event.release.tag_name }}
+                  ECR_REPOSITORY: 'advisingapp/release-automation'
+              run: |
+                  # Build a docker container and
+                  # push it to ECR so that it can
+                  # be deployed to ECS.
+                  docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --target release-automation --platform linux/amd64 .
+                  docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
+                  echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
 
-    # deploy-release-automation:
-    #     name: Deploy and Run Release Automation Service
-    #     needs: [deploy-web, deploy-worker, deploy-scheduler, build-release-automation]
-    #     runs-on: ubuntu-22.04
-    #     environment: staging
+    deploy-release-automation:
+        name: Deploy and Run Release Automation Service
+        needs: [deploy-web, deploy-worker, deploy-scheduler, build-release-automation]
+        runs-on: ubuntu-22.04
+        environment: staging
 
-    #     steps:
-    #         - name: Checkout
-    #           uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #6.0.2
-    #           with:
-    #               submodules: true
-    #               ref: ${{ github.head_ref }}
-    #               token: ${{ secrets.PAT }}
+        steps:
+            - name: Checkout
+              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #6.0.2
+              with:
+                  submodules: true
+                  ref: ${{ github.head_ref }}
+                  token: ${{ secrets.PAT }}
 
-    #         - name: Configure AWS credentials
-    #           uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 #6.1.0
-    #           with:
-    #               aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
-    #               aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
-    #               aws-region: ${{ env.AWS_REGION }}
+            - name: Configure AWS credentials
+              uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 #6.1.0
+              with:
+                  aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
+                  aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
+                  aws-region: ${{ env.AWS_REGION }}
 
-    #         - name: Fill in the new image ID in the Amazon ECS task definition
-    #           id: task-def
-    #           uses: aws-actions/amazon-ecs-render-task-definition@6853cfae8c3a7d978fbf68b5a55453395541dfbb #1.8.5
-    #           with:
-    #               task-definition: 'docker/devops/ecs/advisingapp/advisingapp-release-automation-dev-task-definition.json'
-    #               container-name: 'release-automation'
-    #               image: ${{ needs.build-release-automation.outputs.image }}
+            - name: Fill in the new image ID in the Amazon ECS task definition
+              id: task-def
+              uses: aws-actions/amazon-ecs-render-task-definition@6853cfae8c3a7d978fbf68b5a55453395541dfbb #1.8.5
+              with:
+                  task-definition: 'docker/devops/ecs/advisingapp/advisingapp-release-automation-dev-task-definition.json'
+                  container-name: 'release-automation'
+                  image: ${{ needs.build-release-automation.outputs.image }}
 
-    #         - name: Deploy Amazon ECS task definition
-    #           uses: aws-actions/amazon-ecs-deploy-task-definition@a310a830f5c14e583e35d84e4e1ec7dd177c3c9c #2.6.2
-    #           with:
-    #               task-definition: ${{ steps.task-def.outputs.task-definition }}
-    #               cluster: 'advisingapp-dev'
-    #               desired-count: 1
-    #               run-task: true
-    #               run-task-security-groups: ${{ secrets.RELEASE_AUTOMATION_SECURITY_GROUPS }}
-    #               run-task-subnets: ${{ secrets.RELEASE_AUTOMATION_SUBNETS }}
-    #               run-task-assign-public-IP: 'DISABLED'
-    #               run-task-launch-type: 'FARGATE'
-    #               wait-for-task-stopped: true
+            - name: Deploy Amazon ECS task definition
+              uses: aws-actions/amazon-ecs-deploy-task-definition@a310a830f5c14e583e35d84e4e1ec7dd177c3c9c #2.6.2
+              with:
+                  task-definition: ${{ steps.task-def.outputs.task-definition }}
+                  cluster: 'advisingapp-dev'
+                  desired-count: 1
+                  run-task: true
+                  run-task-security-groups: ${{ secrets.RELEASE_AUTOMATION_SECURITY_GROUPS }}
+                  run-task-subnets: ${{ secrets.RELEASE_AUTOMATION_SUBNETS }}
+                  run-task-assign-public-IP: 'DISABLED'
+                  run-task-launch-type: 'FARGATE'
+                  wait-for-task-stopped: true
